
\section{Simple Tests}
\label{sec:simpletests}

This section discusses our testing suite. We import all modules and test different aspects of the code 
via several QuickCheck queries. 


\begin{code}
{-# LANGUAGE ScopedTypeVariables #-}
module Main where
import Test.QuickCheck
import RegExp
import DFA
import ENFA
import NFA
import Translation
\end{code}
The main function runs all of our tests and prints a one-line explanation for them. 
\begin{code}
main :: IO()
main = do
    print "ZeroStart accepts words starting with 0, for DFA, NFA and ENFA version:"
    test1FA
    print "ZeroStart does not accept other words, for DFA, NFA and ENFA version:"
    test2FA
    print "The reverse of the reverse accepts and rejects the same words:"
    test1ReverseDFA
    print "The reverse of the reverse is isomorphic to the original"
    test2ReverseDFA
    print "Minimize yields an automaton that accepts and rejects the same words:"
    test1MinimizeDFA
    print "Minimize doesn't yield more states:"
    test2MinimizeDFA
    print "cutDFA dfa accepts and rejects the same as dfa:"
    test1CutDFA
    print "Powerset construction yields equivalent DFA for NFA:"
    test1PowNF
    print "Powerset construction yields equivalent DFA for ENFA:"
    test1PowENF
    print "DFA accepts words generated by the corresponding RegExp:"
    test1DFtoReg
    print "DFA does not accept words generated by the RegExp corresponding to the complement DFA:"
    test2DFtoReg
    print "ENFA corresponding to RegExp accepts words generated from RegExp:"
    test1RegtoENF
    print "Composition of translations yields equivalent DFA for DFA:"
    test1DFeqv
    print "Complement RegExps don't generate the same word:"
    test1CompRegx
    print "Complement on different RegExp:"
    test2CompRegx
    print "Minimised automata generated from a RegExp accept words from said RegExp:"
    testMinimizeMore
\end{code}
First we start by defining some example NFA-s and $\epsilon$-NFA-s similar to the previously seen DFA 
called zeroStart, that accept the same language. We also add a further example for a DFA. 
\begin{code}
zeroStartNF:: NFA Int
zeroStartNF = NFA [0,1,2, 3] ['0', '1'] deltazeroNF 0 [1] where
    deltazeroNF:: Symbol-> Int -> [Int]
    deltazeroNF char st
     | st == 0 && char == '0' = [1]
     | st == 0 && char == '1' = [2, 3]
     | st == 1 = [1]
     | st == 2 = [2, 3]
     | st == 3 = [3]
     | otherwise = [-1] --added to avoid hlint warning 'pattern matches are non-exhaustive'

zeroStartENF:: ENFA Int
zeroStartENF = ENFA [0,1,2, 3] ['0', '1'] deltazeroNF [(3,2), (2,3)] 0 [1] where
    deltazeroNF:: Symbol-> Int -> [Int]
    deltazeroNF char st
     | st == 0 && char == '0' = [1]
     | st == 0 && char == '1' = [2, 3]
     | st == 1 = [1]
     | st == 2 = [2, 3]
     | st == 3 = [3]
     | otherwise = [-1]

dfa2:: DFA Int
dfa2 = DFA [0,1,3] "01" del2 3 [0] where
    del2 char st  
      | char =='0' && st == 0 = 3
      | char =='0' && st == 1 = 0
      | char =='0' && st == 3 = 3
      | char =='1' && st == 0 = 1
      | char =='1' && st == 1 = 3
      | char =='1' && st == 3 = 3
      | otherwise = -1

\end{code} 
Note the regular expression for the language of words starting with $0$ is $0(0+1)^*$. 
We generate words from this expression and test if all $3$ of our example automata for this language accept
the generated words. Next, we generate words from the complement language, which has the regular expression $\epsilon + 1(0+1)^*$
and test if the automata reject these words.
\begin{code}
test1FA :: IO ()
test1FA = quickCheck (forAll (generateString (Con (R "0") (Star (Union (R "0") (R "1"))))) 
                        (\w -> zeroStart `evaluate` w && zeroStartNF `evaluateNF` w  &&  
                        zeroStartENF `evaluateENF` w ))
test2FA :: IO ()
test2FA = quickCheck (forAll (generateString (Union Epsilon (Con (R "1") (Star (Union (R "0") (R "1")))))) 
                        (\w -> not (zeroStart `evaluate` w) && not (zeroStartNF `evaluateNF` w)  &&  not(
                        zeroStartENF `evaluateENF` w )))
\end{code}
Here we test the toolkit for obtaining the minimal DFA for a language. Test if the reverse of the reverse DFA 
accept the same words as the original DFA. We go further and use the brozowski function
to test if they are isomorphic.  We then test if a DFA and its corresponding minimal 
DFA accept the same words. We finish by testing that the minimal DFA has always at most
as many states as the original DFA. We also test the cutDFA function. We check if the 
DFA after cutting accepts the same words as the original DFA. We generate arbitrary DFAs for these. 
\begin{code}
test1ReverseDFA :: IO ()
test1ReverseDFA = quickCheck (\r (d:: DFA Int)  -> forAll (generateString r) (\w -> d `evaluate` w == (reverseDFA . reverseDFA ) d `evaluate` w ))
test2ReverseDFA :: IO ()
test2ReverseDFA = quickCheck (\(d :: DFA Int) -> brzozowski d ((reverseDFA . reverseDFA) d) )
test1MinimizeDFA :: IO ()
test1MinimizeDFA = quickCheck (\r (d :: DFA Int) -> forAll (generateString r) (\w -> d `evaluate` w == minimizeDFA d `evaluate` w ))
test2MinimizeDFA :: IO ()
test2MinimizeDFA = quickCheck (\ (d :: DFA Int) -> length (states d) >= length (states (minimizeDFA d)))
test1CutDFA :: IO ()
test1CutDFA = quickCheck (\r (d :: DFA Int) -> forAll (generateString r) (\w -> d `evaluate` w == cutDFA d `evaluate` w ))

\end{code}
We now test the powerset construction. We test if an NFA accepts the same binary strings as
its powerset construct. We repeat for $\epsilon$-NFAs. We generate arbitrary NFAs and $\epsilon$-NFAs for this.
\begin{code}
test1PowNF :: IO ()
test1PowNF = quickCheck (forAll (generateString (Union (R "0") (R "1"))) 
                            (\w (enf:: NFA Int) -> evaluateNF enf w == evaluate (nfaToDFA enf) w) )

test1PowENF :: IO ()
test1PowENF = quickCheck (forAll (generateString (Union (R "0") (R "1"))) 
                            (\w (enf:: ENFA Int) -> evaluateENF enf w == evaluate (enfaToDFA enf) w) )
\end{code}

We now test the translation from DFA to RegExp. We check whether a DFA accepts words generated from
the corresponding regular expression and that it does not accept words generated from the regular expression corresponding to 
the DFA with complement accept states. We generate arbitrary DFAs for this. 

\begin{code}
test1DFtoReg :: IO ()
test1DFtoReg = quickCheck (\ (df:: DFA Int) -> if dfaToRegExp df /= Empty then 
                forAll (generateString (dfaToRegExp df)) (\w -> df `evaluate` w) else property True)

test2DFtoReg :: IO ()
test2DFtoReg = quickCheck ( \ (df:: DFA Int) -> if dfaToRegExp (flipDFA df) /= Empty then 
                forAll (generateString (dfaToRegExp (flipDFA df))) (not . evaluate df ) else property True)
\end{code}

We now test the translation from RegExp to $\epsilon$-NFA. We check whether the $\epsilon$-NFA corresponding
to a regular expression accepts words generated from the the expression. We generate arbitrary regular expressions
 for this.

\begin{code}
test1RegtoENF :: IO ()
test1RegtoENF = quickCheck ( \ (reg:: RegExp) -> forAll (generateString reg) 
                        (\w -> regExpToENFA reg `evaluateENF` w))
\end{code}

We put everything together and test whether a DFA and the DFA obtained from translating to regular expressions, 
then to $\epsilon$-NFA and back to DFA are equivalent. We test it on our two example DFA-s.
We also calculate complement regular expressions by translating to DFAs, taking the complement of accept states
and translating back to regular expressions. We test such complement expressions don't yield the same words. We test
this on $2$ toy expressions. We also combine our translations by the minimal DFA toolkit and check that the 
minimal DFA corresponding to a regular expression accepts the words generated from it. 
\begin{code}
test1DFeqv :: IO ()
test1DFeqv = quickCheck (forAll (generateString (Union (R "0") (R "1"))) 
                (\w -> evaluate dfa2 w == evaluate (func dfa2) w &&  evaluate zeroStart w == evaluate (func zeroStart) w)) where
                    func = enfaToDFA . regExpToENFA . dfaToRegExp

test1CompRegx :: IO ()
test1CompRegx = quickCheck (forAll (generateString reg) (\w -> forAll (generateString (creg reg))(/= w))) where
                    creg = dfaToRegExp . makeIntDFA . flipDFA . enfaToDFA . regExpToENFA
                    reg = Union Epsilon (Con (R "1") (Star (Union (R "0") (R "1"))))

test2CompRegx :: IO ()
test2CompRegx = quickCheck (forAll (generateString reg) (\w -> forAll (generateString (creg reg))(/= w))) where
                    creg = dfaToRegExp . makeIntDFA . flipDFA . enfaToDFA . regExpToENFA
                    reg = Con (Star (R "2")) (Con (R "0") (R "0"))

testMinimizeMore :: IO ()
testMinimizeMore = quickCheck (\r -> forAll (generateString r) (\w -> (minimizeDFA . enfaToDFA . regExpToENFA) r `evaluate` w))  

\end{code}


%To also find out which part of your program is actually used for these tests,
%run \verb|stack clean && stack test --coverage|. Then look for ``The coverage
%report for ... is available at ... .html'' and open this file in your browser.
%See also: \url{https://wiki.haskell.org/Haskell_program_coverage}.
