
\section{Simple Tests}
\label{sec:simpletests}

We create some tests, using QuickCheck to test whether some automata are equal, whether some regular expression 
generates exactly the language of some automaton, and we will add tests that show that our definitions work.


\begin{code}
{-# LANGUAGE ScopedTypeVariables #-}
module Main where
import Test.QuickCheck
import RegExp
import DFA
import ENFA
import NFA
import Translation
--import DFA_raw

main :: IO()
main = do
    print "ZeroStart accepts words starting with 0:"
    test1DF
    print "ZeroStart does not accept other words:"
    test2DF
    print "ZeroStartNF accepts words starting with 0: "
    test1NF
    print "ZeroStartNF does not accept other words:"
    test2NF
    print "ZeroStartENF accepts words starting with 0:"
    test1ENF
    print "ZeroStartENF does not accept other words:"
    test2ENF
    print "Powerset construction yields equivalent DFA for NFA:"
    test1PowNF
    print "Powerset construction yields equivalent DFA for ENFA:"
    test1PowENF
    print "DFA accepts words generated by the corresponding RegExp:"
    test1DFtoReg
    print "DFA does not accept words generated by the RegExp corresponding to the complement DFA:"
    test2DFtoReg
    print "ENFA corresponding to RegExp accepts words generated from RegExp:"
    test1RegtoENF
    print "Composition of transitions yields equivalent DFA for DFA:"
    test1DFeqv
    print "Complement RegExps don't generate the same word:"
    test1CompRegx
    print "Complement on different RegExp:"
    test2CompRegx
    print "The reverse of the reverse accepts and rejects the same words:"
    test1ReverseDFA
    print "The reverse of the reverse is isomorphic to the original"
    test2ReverseDFA
    print "Minimize yields an automaton that accepts and rejects the same words:"
    test1MinimizeDFA
    print "Minimised automata generated from a RegExp accept words from said RegExp"
    testMinimizeMore
    print "Minimize doesn't yield more states"
    test2MinimizeDFA
    print "cutDFA dfa accepts and rejects the same as dfa"
    test1CutDFA
<<<<<<< HEAD
=======


>>>>>>> 7a82919 (Transition -> Translation)
    
\end{code}
The first test whether the example DFA, called zeroStart indeed accepts the strings 
starging with $0$. Note the regular expression for this language is $0(0+1)*$. 
We do the same for slightly modified NFA and ENFA versions of zeroStart. 

\begin{code}
zeroStartNF:: NFA Int
zeroStartNF = NFA [0,1,2, 3] ['0', '1'] deltazeroNF 0 [1] where
    deltazeroNF:: Symbol-> Int -> [Int]
    deltazeroNF char st
     | st == 0 && char == '0' = [1]
     | st == 0 && char == '1' = [2, 3]
     | st == 1 = [1]
     | st == 2 = [2, 3]
     | st == 3 = [3]
     | otherwise = [-1]

zeroStartENF:: ENFA Int
zeroStartENF = ENFA [0,1,2, 3] ['0', '1'] deltazeroNF [(3,2), (2,3)] 0 [1] where
    deltazeroNF:: Symbol-> Int -> [Int]
    deltazeroNF char st
     | st == 0 && char == '0' = [1]
     | st == 0 && char == '1' = [2, 3]
     | st == 1 = [1]
     | st == 2 = [2, 3]
     | st == 3 = [3]
     | otherwise = [-1]

dfa2:: DFA Int
dfa2 = DFA [0,1,3] "01" del2 3 [0] where
    del2 char st  
      | char =='0' && st == 0 = 3
      | char =='0' && st == 1 = 0
      | char =='0' && st == 3 = 3
      | char =='1' && st == 0 = 1
      | char =='1' && st == 1 = 3
      | char =='1' && st == 3 = 3
      | otherwise = -1

-- test
test1DF :: IO ()
test1DF = quickCheck (forAll (generateString (Con (R "0") (Star (Union (R "0") (R "1"))))) 
                        (\w -> zeroStart `evaluate` w))

test1NF :: IO ()
test1NF = quickCheck (forAll (generateString (Con (R "0") (Star (Union (R "0") (R "1"))))) 
                        (\w -> zeroStartNF `evaluateNF` w ))

test1ENF :: IO ()
test1ENF = quickCheck (forAll (generateString (Con (R "0") (Star (Union (R "0") (R "1"))))) 
                        (\w -> zeroStartENF `evaluateENF` w ))

\end{code}

We now test that words generated from the RegExp for the complement are not accepted. 
Note the RegExp for the complement language is $\epsilon + 1(0+1)*$

\begin{code}
test2DF :: IO ()
test2DF = quickCheck (forAll (generateString (Union Epsilon (Con (R "1") (Star (Union (R "0") (R "1")))))) 
                        (not . evaluate zeroStart))

test2NF :: IO ()
test2NF = quickCheck (forAll (generateString (Union Epsilon (Con (R "1") (Star (Union (R "0") (R "1")))))) 
                        (not . evaluateNF zeroStartNF))

test2ENF :: IO ()
test2ENF = quickCheck (forAll (generateString (Union Epsilon (Con (R "1") (Star (Union (R "0") (R "1")))))) 
                        (not . evaluateENF zeroStartENF))
\end{code}

We now test the powerset construction. We test if an NFA accepts the same binary strings as
its powerset construct. We repeat for ENFA-s. We generate arbitrary NFA-s and ENFA-s for this.
\begin{code}
test1PowNF :: IO ()
test1PowNF = quickCheck (forAll (generateString (Union (R "0") (R "1"))) 
                            (\w (enf:: NFA Int) -> evaluateNF enf w == evaluate (nfaToDFA enf) w) )

test1PowENF :: IO ()
test1PowENF = quickCheck (forAll (generateString (Union (R "0") (R "1"))) 
                            (\w (enf:: ENFA Int) -> evaluateENF enf w == evaluate (enfaToDFA enf) w) )
\end{code}

We now test the transition from DFA to RegExp. We check whether a DFA accepts words generated from
the corresponding RegExp and that it does not accept words generated from the RegExp corresponding to 
the complement DFA. We generate arbitrary DFA-s for this. 

\begin{code}
test1DFtoReg :: IO ()
test1DFtoReg = quickCheck (\ (df:: DFA Int) -> if dfaToRegExp df /= Empty then 
                forAll (generateString (dfaToRegExp df)) (\w -> df `evaluate` w) else property True)

test2DFtoReg :: IO ()
test2DFtoReg = quickCheck ( \ (df:: DFA Int) -> if dfaToRegExp (flipDFA df) /= Empty then 
                forAll (generateString (dfaToRegExp (flipDFA df))) (not . evaluate df ) else property True)
\end{code}

We now test the transition from RegExp to $\epsilon$-NFA. We check whether the $\epsilon$-NFA corresponding
to a RegExp accepts words generated from the RegExp. We generate arbitrary RegExps- for this.

\begin{code}
test1RegtoENF :: IO ()
test1RegtoENF = quickCheck ( \ (reg:: RegExp) -> forAll (generateString reg) 
                        (\w -> regExpToENFA reg `evaluateENF` w))
\end{code}

We put everything together and test whether a DFA and the DFA obtained from transitioning to RegExp, 
then to $\epsilon$-NFA and back to DFA are equivalent. We test it on our two example DFA-s.
We also calculate complement RegExp-s by flipping the corresponding DFA accept states
and test for a for 2 RegExps that they don't generate the same words.
\begin{code}
test1DFeqv :: IO ()
test1DFeqv = quickCheck (forAll (generateString (Union (R "0") (R "1"))) 
                (\w -> evaluate dfa2 w == evaluate (func dfa2) w &&  evaluate zeroStart w == evaluate (func zeroStart) w)) where
                    func = enfaToDFA . regExpToENFA . dfaToRegExp



test1CompRegx :: IO ()
test1CompRegx = quickCheck (forAll (generateString reg) (\w -> forAll (generateString (creg reg))(/= w))) where
                    creg = dfaToRegExp . makeIntDFA . flipDFA . enfaToDFA . regExpToENFA
                    reg = Union Epsilon (Con (R "1") (Star (Union (R "0") (R "1"))))

test2CompRegx :: IO ()
test2CompRegx = quickCheck (forAll (generateString reg) (\w -> forAll (generateString (creg reg))(/= w))) where
                    creg = dfaToRegExp . makeIntDFA . flipDFA . enfaToDFA . regExpToENFA
                    reg = Con (Star (R "2")) (Con (R "0") (R "0"))



test1ReverseDFA :: IO ()
test1ReverseDFA = quickCheck (\r (d:: DFA Int)  -> forAll (generateString r) (\w -> d `evaluate` w == (reverseDFA . reverseDFA ) d `evaluate` w ))
test2ReverseDFA :: IO ()
test2ReverseDFA = quickCheck (\(d :: DFA Int) -> brzozowski d ((reverseDFA . reverseDFA) d) )
test1MinimizeDFA :: IO ()
test1MinimizeDFA = quickCheck (\r (d :: DFA Int) -> forAll (generateString r) (\w -> d `evaluate` w == minimizeDFA d `evaluate` w ))
test2MinimizeDFA :: IO ()
test2MinimizeDFA = quickCheck (\ (d :: DFA Int) -> length (states d) >= length (states (minimizeDFA d)))

testMinimizeMore :: IO ()
testMinimizeMore = quickCheck (\r -> forAll (generateString r) (\w -> (minimizeDFA . enfaToDFA . regExpToENFA) r `evaluate` w))  


test1CutDFA :: IO ()
test1CutDFA = quickCheck (\r (d :: DFA Int) -> forAll (generateString r) (\w -> d `evaluate` w == cutDFA d `evaluate` w ))
<<<<<<< HEAD
=======

>>>>>>> 7a82919 (Transition -> Translation)
\end{code}


%To also find out which part of your program is actually used for these tests,
%run \verb|stack clean && stack test --coverage|. Then look for ``The coverage
%report for ... is available at ... .html'' and open this file in your browser.
%See also: \url{https://wiki.haskell.org/Haskell_program_coverage}.
