name: finite-automata
version: 0.1.0.0
synopsis: Finite Automata and Regular Expressions
description: See finite-automata.tex
maintainer: Vince Velkey <vince.velkey@student.uva.nl>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - finite-automata

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - finite-automata
      - QuickCheck
      - hspec
