module DFA_raw where

import Data.List()
import System.Random
import DFA
import ENFA
import NFA()
import RegExp
import Transitions
import Test.QuickCheck()



-- Toy example: accepts all strings starting with 0

-- Toy example: check if the word generated by (01)* gets accepted by DFA zeroStart
-- A function to use for testing

epENF :: ENFA Int
epENF = ENFA [0] [] (\_ _ -> []) [] 0 [0]

qc :: (Eq a, Ord a) => DFA a -> RegExp -> Int -> IO ()
qc _ _ 0 = print "No counterexample found"
qc dfa ex n =  do
  s <- generateWord ex
  if evaluate dfa s
    then qc dfa ex (n-1)
    else 
      if s == "" 
      then print "The DFA rejected the empty string"
      else print ("the DFA rejected " ++ s) 

qcToy :: IO ()
qcToy = do
  s <- generateWord (Star (Con (R "0") (R "1")))
  if evaluate zeroStart s 
    then print ("zeroStart accepts " ++ s) 
    else print ("zeroStart rejects " ++ s)

generateWord :: RegExp -> IO String
generateWord = generateWord' . simplify
  where 
  generateWord' Empty = error "cannot generate from empty language"
  generateWord' Epsilon = pure ""
  generateWord' (R xs) = pure xs
  generateWord' (Union r1 r2) = do
    i <- getStdRandom (randomR (0,1::Int))
    [generateWord' r1, generateWord' r2] !! i
  generateWord' (Con r1 r2) = do
    one <- generateWord' r1
    two <- generateWord' r2
    return (one ++ two)
  generateWord' (Star r) = do
    i <- getStdRandom (randomR (0,1::Int))
    [generateWord' Epsilon, generateWord' (Con r (Star r))] !! i
  generateWord' (Plus r) = generateWord' (Con r (Star r)) 

-- More toys
qc1 :: IO ()
qc1 = qc zeroStart (Con (R "0") (Star (R "1"))) 100
qc2 :: IO ()
qc2 = qc zeroStart (Plus (Con (R "0") (R "1") )) 100
qc3 :: IO ()
qc3 =  qc zeroStart (Star (Con (R "0") (R "1") )) 100
qc4 :: IO ()
qc4 = qc zeroStart (Star (Union (R "a") (R "1"))) 100

reg' :: RegExp
reg' = transDFAtoRegExp zeroStart

enf :: ENFA Int
enf = regExpToENFA reg' 

df :: DFA [Int]
df = enfToDf enf









 
