\section{Translation functions}\label{sec:Trans}

Here we implement all the algorithms that translate betwen FSAs and regular expressions. For each instance, 
we give a short theoretical background and then discuss our implementation.

\begin{code}
module Translation where
import Data.List 
import NFA
import DFA
import ENFA
import RegExp
import Data.Maybe (fromJust)
\end{code}
\subsection{The Powerset construction}\label{powerset}
As stated earlier, ($\epsilon$)-NFAs and DFA-s are equivalent in their computing power. This fact is shown by constructing an equivalent DFA from an ($\epsilon$) - NFA. This procedure is called the powerset construction, which we detail here.  

\begin{definition}{(Powerset construction - NFA-s)}
	Given an NFA $N = (Q_n, \Sigma, \delta_n, q_0, F_n)$, its powerset construct is a DFA $D = (\mathcal{P}(Q_n), \Sigma, \delta, S, F_D )$, where
	\begin{itemize}
		\item $\mathcal{P}(Q_n)$ is the powerset of $Q_n$, 
		\item $S = \{q_0\}$
		\item $F_D = \{R\subset Q_N \colon S\cap F_n \neq \emptyset\}$
		\item $\delta_D(R, \sigma) = \cup_{s\in R} \delta_N(s, \sigma)$
	\end{itemize}
\end{definition}
For $\epsilon$-NFA-s the powerset construct is defined similarly, with the distinction that $S = \mathrm{ecl}(\{q_0\})$ and $\delta_D(R, \sigma) = \mathrm{ecl}(\cup_{s\in R} \delta_N(s, \sigma))$. Here, $\mathrm{ecl}(A)$ stands for the set of states reachable from $A$ via $\epsilon$-transitions.

\begin{theorem}
	An ($\epsilon$)-NFA $N$ and its powerset construct are equivalent. 
\end{theorem}
We implement the powerset construction for NFA-s. The states of the powerset construct are sublists of states of the NFA. 
Note that the standard powerset construction is greedy: it introduces exponentially many states. For running purposes, we cut the resulting 
DFA by our cutDFA function. In some examples, this could cut down a DFA on $2^{19}$ states to as few as $10$.
\begin{code}
nfaToDFA:: (Eq a, Ord a) => NFA a -> DFA [a]
nfaToDFA (NFA sts alph del strt ac) = 
  cutDFA $ DFA sortedStates alph del' (sort [strt]) [st | st <- sortedStates,  intersect st ac /= []] where
    del' sy ls = unionL [del sy l | l <- ls] 
    sortedStates = map sort $ subsequences sts
\end{code}

For $\epsilon$-NFA-s, we need to take care to take $\epsilon$-closures at each relevant step. 

\begin{code}
enfaToDFA:: (Eq a, Ord a) => ENFA a -> DFA [a]
enfaToDFA (ENFA sts alph del eps strt ac) = let nf = ENFA sts alph del eps strt ac in 
  cutDFA $ DFA sortedStates alph del' (rtClose nf (sort [strt])) [st | st <- sortedStates,  intersect st ac /= []] where
    del' sy ls = let nf = ENFA sts alph del eps strt ac in rtClose nf ( unionL [del sy l | l <- ls] )
    sortedStates = map sort $ subsequences sts
                                                              
\end{code}
\subsection{From regular expressions to $\epsilon$-NFAs}
The translation from regular expressions to $\epsilon$-NFAs we implemented is done by recursion on the structure of regular expressions. First we define automata for the basic forms of regular expressions: $\empty$, $\epsilon$ and the list of symbols. Then for the complex expressions, we combine the automata of its components accordingly. This way we get an automaton that exactly recognizes the language generated by the regular expression.

\begin{theorem}
Let $r$ be any regular expression. Then there exists an $\epsilon$-NFA $N$ such that $\mathcal{L}(r)=\mathcal{L}(N)$.
\end{theorem} 
\begin{proof}
Let $r$ be any regular expression on any alphabet $\Sigma$. We use structural induction on $r$.
\begin{itemize}
\item For $r:=\emptyset$, consider $\epsilon$-NFA $N=(\{q\},\Sigma,\emptyset,\emptyset,q,\emptyset)$. Recall that $\mathcal{L}(r)=emptyset$. $N$ rejects on every input as no path can end up in an accepting state, because there are no accepting states. Hence $\mathcal{L}(N)=\emptyset$.
\item For $r:=\epsilon$, recall that $\mathcal{L}(r)=\{\epsilon\}$. Now consider $\epsilon$-NFA $N= (\{q\}, \emptyset, \emptyset, \emptyset, q, \{q\})$. On the empty input, $N$ ends in the start state, which is also an accepting state, so $N$ accepts. On any other input, $N$ rejects as no outgoing arrows are defined for the starting state. Hence $\mathcal{L}(N)=\{\epsilon\}$. 
\item For $r:= a$ with $a\in\Sigma$, recall that $\mathcal{L}(r)=\{a\}$. Construct $N=(\{s,t\}, \Sigma, \{(s, a, t\},\emptyset,s,\{t\})$. Observe that $N$ rejects the empty string, as the initial state is not accepting. Because there is just one transition, if $N$ reads anything other than $a$, it will reject. If $N$ reads $a$ and anything after that, it will also reject. If it just reads $a$ and nothing more, $N$ will accept as $t$ is accepting. Hence $\mathcal{L}(N)=\{a\}$. 
\end{itemize}
\end{proof}


Now we implement the translation from RegExp to ENFA.
\begin{code}
regExpToENFA :: RegExp -> ENFA Int
regExpToENFA Empty   = ENFA [1] [] (\_ _ -> []) [] 1 []
regExpToENFA Epsilon = ENFA [1] [] (\_ _ -> []) [] 1 [1]
regExpToENFA (R [])  = ENFA [1] [] (\_ _ -> []) [] 1 [1]
regExpToENFA (R xs)  = ENFA [0..length xs] (nub xs) delta2 [] 0 [length xs] where
  delta2 symbol state | state >= length xs || state < 0 = []
                      | xs !! state == symbol = [state + 1]
                      | otherwise = []
regExpToENFA (Union r1 r2) = regExpToENFA r1 `unionENFA` makeDisjoint (regExpToENFA r1) (regExpToENFA r2)
regExpToENFA (Star r) = starENFA (regExpToENFA r)
regExpToENFA (Con r1 r2) = regExpToENFA r1 `concatENFA` makeDisjoint (regExpToENFA r1) (regExpToENFA r2)
regExpToENFA (Plus r) = regExpToENFA r `concatENFA` makeDisjoint (regExpToENFA r) (starENFA (regExpToENFA r))


-- function that takes two ENFAs and outputs a relabeling of the second ENFA such that the states of both become disjoint
makeDisjoint :: ENFA Int -> ENFA Int -> ENFA Int
makeDisjoint n1 n2 = ENFA states' alphabet' delta' epT start' accept where
  add | minimum (statesENF n2) <= 0 = negate (minimum (statesENF n2)) + (maximum (statesENF n1 ++ statesENF n2) + 1)
      | otherwise = maximum (statesENF n1 ++ statesENF n2) + 1
  states' = map (+ add) (statesENF n2)
  alphabet' = alphabetENF n2
  delta' sym state = map (+ add) (deltaENF n2 sym (state - add))
  epT = [(s + add, t + add) | (s,t) <- epTrans n2 ] 
  start' = startENF n2 + add
  accept = map (+ add) (acceptstateENF n2)


unionENFA :: ENFA Int -> ENFA Int -> ENFA Int-- Use only if states are disjoint
unionENFA n1 n2 = ENFA states'' alphabet2 delta'' epT start'' accept where
  states'' = start'' : statesENF n1 ++ statesENF n2
  alphabet2 = alphabetENF n1 `union` alphabetENF n2
  delta'' sym st = deltaENF n1 sym st ++ deltaENF n2 sym st
  epT = epTrans n1 ++ epTrans n2 ++ [(start'', startENF n1), (start'', startENF n2)]
  start'' = maximum (statesENF n2 ++ statesENF n1) + 1 
  accept = acceptstateENF n1 ++ acceptstateENF n2

starENFA :: ENFA Int -> ENFA Int
starENFA n = ENFA (statesENF n) (alphabetENF n) (deltaENF n) ep (startENF n) (acceptstateENF n)  where
  ep = epTrans n ++ [(startENF n, s)| s <- acceptstateENF n] ++ [(s, startENF n) | s <- acceptstateENF n]

concatENFA :: ENFA Int -> ENFA Int -> ENFA Int -- Use only if states are disjoint again
concatENFA n1 n2 = ENFA states4 alphabet'' delta3 epT start3 accept where
  states4 = statesENF n1 ++ statesENF n2
  alphabet'' = alphabetENF n1 `union` alphabetENF n2
  delta3 sym st = deltaENF n1 sym st ++ deltaENF n2 sym st
  epT = epTrans n1 ++ epTrans n2 ++ [(s, startENF n2) | s <- acceptstateENF n1]
  start3 = startENF n1
  accept = acceptstateENF n2
\end{code}

Finally, we turn to implement DFA to RegExp. AFL-notes version:

First we rename the states so that they are now integers $1\dots n$ where $n$ is the amount of states.
For that we use the following function:
\begin{code}

makeIntDFA :: (Eq a, Ord a) => DFA a -> DFA Int
makeIntDFA dfa = DFA sts alph delt strt acceptst 
  where sts = [1..length (states dfa)]
        alph = alphabet dfa
        delt sym i  = indX $ delta dfa sym (states dfa !! (i-1))
        strt = indX (start dfa)
        acceptst = [indX s | s <- acceptstate dfa]
        indX s = fromJust (elemIndex s (states dfa)) + 1

-- simplify to make the result a bit more readable 
dfaToRegExp :: Ord a => DFA a -> RegExp
dfaToRegExp dfa = simplify $ regExpUnion [rijk dfaInt (start dfaInt) f (length $ states dfaInt) | f <- acceptstate dfaInt ]
  where dfaInt = (makeIntDFA . minimizeDFA) dfa

-- Here is the magic from the notes:
rijk :: DFA Int -> Int -> Int -> Int -> RegExp
rijk dfa i j 0 | i == j  = regExpUnion $ Epsilon : labels
               | null labels = Empty
               | length labels == 1 = head labels
               | otherwise = foldr Union (head labels) (tail labels)          
  where labels =  [R [x] | x <- alphabet dfa, delta dfa x i == j]
rijk dfa i j k = Union (rijk dfa i j (k-1)) (Con (rijk dfa i k (k-1)) (Con (Star $ rijk dfa k k (k-1)) (rijk dfa k j (k-1))))

\end{code}


Brzozowski's algorithm for minimising DFA's \cite{Brzozowski1962CanonicalRE}

\begin{code}



minimizeDFA :: Ord a => DFA a -> DFA [Int]
minimizeDFA df | all (`elem` acceptstate df) (reachables df)  = DFA [[0]] (alphabet df) (const (const [0])) [0] [[0]] 
               |  otherwise = (reverseDFA . reverseDFA) df 

  
reverseDFA :: Ord a => DFA a -> DFA [Int]
reverseDFA d = enfaToDFA' $ ENFA sts alph delt ep st acc where
    e = singleAccept $ cutDFA d
    sts = statesENF e
    alph = alphabetENF e
    delt sym s = [t | t <- statesENF e, s `elem` deltaENF e sym t] 
    ep = [(s, t) | (t,s) <- epTrans e ]
    st = head $ acceptstateENF e
    acc = [startENF e]
    enfaToDFA' nf@(ENFA sts' alph' del eps strt ac) = 
      cutDFA $ DFA sortedStates alph' del' (rtClose nf (sort [ t | (s, t) <- eps, s == strt])) [st' | st' <- sortedStates,  intersect st' ac /= []] where
      del' sy ls = rtClose nf ( unionL [del sy l | l <- ls] )
      sortedStates = map sort $ subsequences sts'
  
singleAccept :: Ord a => DFA a -> ENFA Int
singleAccept d = ENFA sts alph delt ep st acc where 
    d' = makeIntDFA d 
    newAccept = maximum (states d') + 1
    sts = newAccept : states d'
    alph = alphabet d'
    delt sym t | t == newAccept = []
               | otherwise =  [delta d' sym t]
    ep = [(f, newAccept) | f <- acceptstate d']
    st = start d'
    acc = [newAccept]

-- Checks whether the reachable states of two DFA's are Isomorphic
brzozowski :: (Ord a, Ord b) => DFA a -> DFA b -> Bool
brzozowski d d' = alphabet d == alphabet d' && 
  (null (acceptstate m) && null (acceptstate m')) ||
   isIsomorphTo (start m) (start m') [] where
    m = minimizeDFA d
    m' = minimizeDFA d'
    isIsomorphTo s s' is = 
      (s,s') `elem` is || (s `elem` acceptstate m) == (s' `elem` acceptstate m') &&
      all (\sym -> isIsomorphTo (delta m sym s) (delta m' sym s') ((s,s'):is)) (alphabet m) 
\end{code}